version: '3'
services:
  library-mysql:
    build:
      context: .
      dockerfile: Dockerfile-mysql
    image: library-mysql:0.0.1-compose
    restart: always
    volumes:
      - ./mysql-data:/var/lib/mysql
  library-backend:
    build: .
    image: library-backend:0.0.1-compose
    environment:
      - DB_URL=library-mysql
      - DB_PORT=3306
      - DB_NAME=mysql_db
      - DB_USERNAME=root
      - DB_PASSWORD=root
    depends_on:
      - library-mysql
    ports:
      - "8080:8080"